### PR TITLE
WIP: feat(tag): add tag blot

### PR DESCRIPTION
**Pull request by mayyyc**
#192

### CODE REVIEW

**Comment by mayyyc** [comment]
@robertu7 wonder if you know why the build failed, it failed at Slack Notification.

**Comment by robertu7** [comment]
@mayyyc I guess it was caused by [environment missing](https://github.com/thematters/matters-editor/blob/develop/.github/workflows/build_and_publish.yml#L14). 🤔

**Comment by mayyyc** [comment]
@robertu7 how do i resolve that?

**Comment by robertu7** [comment]
@mayyyc we have fixed this via https://github.com/thematters/matters-editor/pull/213, please recreate the PR.

**Comment by guoliu** [comment]
@mayyyc @robertu7 how should we move this PR forward, do we have to create another PR?

**Comment by mayyyc** [comment]
@guoliu i will create another pr, im also working on the [mention module](https://github.com/thematters/matters-editor/blob/develop/src/modules/mention.ts) should i push in the same pr or should i create another one so i can merge this one in?

**Comment by guoliu** [comment]
> @guoliu i will create another pr, im also working on the [mention module](https://github.com/thematters/matters-editor/blob/develop/src/modules/mention.ts) should i push in the same pr or should i create another one so i can merge this one in?

@mayyyc the current PR should be good, lets review and merge it first 🌿

**Pull request closed without merging**
